### ISSUE TITLE
[QUESTION] 11.000 Images

### ISSUE THREAD

**Issue by hirbod** [Luehang/react-native-camera-roll-gallery#4]
Hi,

do you have any setting or recommendation for a CameraRoll with 11k images? For me, the Flatlist showing the images is quite ok, but its unusable when I open the "Modal". Is there also a way to disable the modal opening? I just want to get the image when I tap it in order to do some other actions.

**Comment by Luehang** [comment]
Hi,

There has been new major updates.  Please update to latest and follow best practices for rendering extremely large datasets.

<br/>

```bash
$ npm install --save react-native-camera-roll-gallery@latest
```

or

```bash
$ yarn add react-native-camera-roll-gallery@latest
```

<br/>
<br/>
<br/>

---
<br/>
<br/>
<br/>

## :tada: Example Usage Customization

**Version \*4.0.0 update**

> If you like [`react-native-camera-roll-gallery`](https://github.com/Luehang/react-native-camera-roll-gallery), please be sure to give it a star at [GitHub](https://github.com/Luehang/react-native-camera-roll-gallery). Thanks.

```javascript
import CameraRollGallery from "react-native-camera-roll-gallery";

//...
render() {
    return (
        <CameraRollGallery
            enableCameraRoll={false} // default true
            // Get data logic goes here.
            // This will get trigger initially
            // and when it reached the end
            // if there is more.
            onGetData={(fetchParams, resolve) => {
                resolve({
                    assets: [
                        // Can be used with different image object fieldnames.
                        // Ex. source, source.uri, uri, URI, url, URL
                        { uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-blonde-hair-478544.jpg" },
                        // { source: require("yourApp/image.png"),
                        //     // IMPORTANT: It is REQUIRED for LOCAL IMAGES
                        //     // to include a dimensions field with the
                        //     // actual width and height of the image or
                        //     // it will throw an error.
                        //     dimensions: { width: 1080, height: 1920 } },
                        { source: { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg" } },
                        { uri: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg" },
                        { URI: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg" },
                        { url: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg" },
                        { URL: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg" },
                    ],
                    pageInfo: {
                        hasNextPage: false
                    }
                });
            }}
        />
    );
}
//...
```

<br/>
<br/>
<br/>

---
<br/>
<br/>
<br/>

## :tada: Example Usage With Provided CameraRoll

:information_source: Additional installation is required to install additional package and link binaries. Follow the [Installation section](#gem-installation-for-provided-cameraroll).

> If you like [`react-native-camera-roll-gallery`](https://github.com/Luehang/react-native-camera-roll-gallery), please be sure to give it a star at [GitHub](https://github.com/Luehang/react-native-camera-roll-gallery). Thanks.

```javascript
import CameraRollGallery from "react-native-camera-roll-gallery";

//...
render() {
    return (
        <CameraRollGallery />
    );
}
//...
```
